name: cicd
on:
  push:
jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner
        id: scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'
          output: 'trivy-output.txt'

      - name: sendFail
    
        if: always() && (steps.scan.outcome == 'failure')
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'IT IS FAIL'

      - name: upload report
        if: always() && (steps.scan.outcome == 'failure')
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          path: trivy-output.txt
          channel: ${{ secrets.SLACK_CHANNEL }}


      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: zhoumix/cicd:test

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1
        with:
          cosign-release: 'v2.1.1'
      - name: Check install!
        run: cosign version

      - name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
          TAGS: zhoumix/cicd:test
        run: cosign sign --yes "${TAGS}@${DIGEST}"

      - name: sendSuccess
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "
          *Image build & signed*\n
          *Name:* Zhou Mingxun\n
          *Matriculation:* A0285974H\n
          *Email:* e1221786@u.nus.edu\n
          *Git:* https://github.com/NuClz/CICD\n
          *Docker:* https://hub.docker.com/repository/docker/zhoumix/cicd/general"